version: '2'
services:
    greenorion-app:
        image: greenorion
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://greenorion-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=greenorion
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    greenorion-mongodb:
        extends:
            file: mongodb.yml
            service: greenorion-mongodb
